---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    openshift:
      common:
        client_binary: "/usr/bin/oc"
        admin_binary: "/usr/bin/oc adm"
    ruby_namespace: "ruby-example"
  tasks:
    - include_role:
        name: casl-ansible/roles/openshift-login
    - include_role:
        name: openshift-applier/roles/openshift-applier
